spring:
  application:
    name: kopring
  datasource:
    url: jdbc:mysql://localhost:3306/kopring
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:logback-spring.xml
