spring:
  application:
    name: kopring
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full

datasource:
    kopring:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/kopring
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    toybatch:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/toyBatch
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
logging:
  config: classpath:logback-spring.xml
