spring:
  application:
    name: kopring
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/kopring
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
            default:
                connectTimeout: 1000
                readTimeout: 1000
                loggerLevel: full

logging:
  config: classpath:logback-spring.xml
