spring:
  jmx:
    enabled: false
  application:
    name: kopring
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full
datasource:
    kopring:
      url: jdbc:log4jdbc:mysql://localhost:3306/kopring
      username: root
      password: rootroot
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 30
        registerMbeans: true
        minimum-idle: 10
    toybatch:
      url: jdbc:log4jdbc:mysql://localhost:3306/toyBatch
      username: root
      password: rootroot
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 5
        registerMbeans: true
        minimum-idle: 1
logging:
  config: classpath:logback-spring.xml
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100 # sliding window size
      permittedNumberOfCallsInHalfOpenState: 10 # half open 상태에서 허용되는 호출 수
      waitDurationInOpenState: 10000 # OPEN -> HALF_OPEN 상태로 전환하기까지 대기 시간
      failureRateThreshold: 60 # 실패 임계치, 60% 이상 실패하면 OPEN 상태로 전환
      eventConsumerBufferSize: 10 # 이벤트 컨슈머 버퍼 크기, GET /actuator/circuitbreakerevents 에서 확인 가능
      registerHealthIndicator: true
      ignore-exceptions:
        - java.lang.IllegalArgumentException
    someShared: # 공유 설정 전용 변수
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    appA:
      baseConfig: default # default 설정을 상속받음
      waitDurationInOpenState: 5000 # 재정의 : OPEN -> HALF_OPEN 상태로 전환하기까지 대기 시간
    appB:
      baseConfig: someShared # someShared 설정을 상속받음
management:
  jmx:
    metrics:
      export:
        domain: "com.practice.kopring"
  endpoints:
    web:
      exposure:
        include: '*'
