spring:
  jmx:
    enabled: false
  application:
    name: kopring
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full
datasource:
    kopring:
      url: jdbc:log4jdbc:mysql://localhost:3306/kopring
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 30
        registerMbeans: true
        minimum-idle: 10
    toybatch:
      url: jdbc:log4jdbc:mysql://localhost:3306/toyBatch
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 5
        registerMbeans: true
        minimum-idle: 1
logging:
  config: classpath:logback-spring.xml
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    appA:
      baseConfig: default
      waitDurationInOpenState: 5000
    appB:
      baseConfig: someShared
management:
  jmx:
    metrics:
      export:
        domain: "com.practice.kopring"
  endpoints:
    web:
      exposure:
        include: '*'
