spring:
  application:
    name: kopring
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
            loggerLevel: full

datasource:
    kopring:
      url: jdbc:log4jdbc:mysql://localhost:3306/kopring
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 30
    toybatch:
      url: jdbc:log4jdbc:mysql://localhost:3306/toyBatch
      username: root
      password: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      configuration:
        maximum-pool-size: 5
logging:
  config: classpath:logback-spring.xml
